### ISSUE TITLE
How to apply this framework to detect only 4 keypoints ? Where I need modify ?

### ISSUE THREAD

**Issue by XiaoLaoDi** [scnuhealthy/Pytorch-Keypoint-Detection#1]
When I try to apply this to 4 keypoints detection, what should I do ?

**Comment by XiaoLaoDi** [comment]
This code is highly prepared for human pose keypoints detection, how should I modify the code ?

**Comment by scnuhealthy** [comment]
你需要修改pytorch的model, 官网有教程说明two-stages网络如何构建，然后数据集建议转换为COCO格式，这样可以使用现有的函数接口去读取数据
