### ISSUE TITLE
关于模型keypointrcnn_resnet50_fpn输出结果的疑问

### ISSUE THREAD

**Issue by Sihan-Song** [scnuhealthy/Pytorch-Keypoint-Detection#5]
你好，我看pytorch官网上说关键点的输出是[x, y, v]的形式，其中v是0/1/2，可是为什么在predict_visualize.py中模型的输出结果中v总是为1呢，并且为什么还有一个keypoints_scores呢？

**Comment by hasayake007** [comment]
v是是否可见1
